In [2]:
import pandas as pd
import numpy as np

Series in Pandas

In [4]:
s = pd.Series([10,20,30,40])

In [5]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

Custom INdex

In [8]:
s = pd.Series([10,20,30], index=['a','b','c'])
print(s)

a    10
b    20
c    30
dtype: int64

In [10]:
print(s['a'])
print(s[0])

10
10

C:\Users\Atul Raj Singh\AppData\Local\Temp\ipykernel_5480\1148839198.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [11]:
data = {"Math": 90, "Physics": 85, "Chemistry":88}

In [15]:
marks = pd.Series(data)
print(data)
print(marks)

{'Math': 90, 'Physics': 85, 'Chemistry': 88}
Math         90
Physics      85
Chemistry    88
dtype: int64

DataFrames in Pandas

In [16]:
data = {"Name":["Aman","Krish","Rohan"],"Age":[22,24,26],"Marks":[85,90,88]}

In [21]:
print(data)
type(data)

{'Name': ['Aman', 'Krish', 'Rohan'], 'Age': [22, 24, 26], 'Marks': [85, 90, 88]}

dict

In [23]:
data_df = pd.DataFrame(data,index = ["Student1","Student2","student3"])
print(data_df)
type(data_df)

           Name  Age  Marks
Student1   Aman   22     85
Student2  Krish   24     90
student3  Rohan   26     88

pandas.core.frame.DataFrame

In [ ]:
data_df.set_index("Name",inplace=True)
# note: if we are setting inplace = true it means we are changing original dataset itselt
print(data_df)

       Age  Marks
Name
Aman    22     85
Krish   24     90
Rohan   26     88

In [30]:
df = pd.DataFrame({"Name":["Aman","Krish","Rohan"],"Age":[22,24,26],"Marks":[85,90,88]})

In [32]:
print(df)

    Name  Age  Marks
0   Aman   22     85
1  Krish   24     90
2  Rohan   26     88

In [ ]:
df.head()
# note if the no of rows is less than 5 then output will print head and tail both

    Name  Age  Marks
0   Aman   22     85
1  Krish   24     90
2  Rohan   26     88

In [ ]:
df.tail()
# note if the no of rows is less than 5 then output will print head and tail both

    Name  Age  Marks
0   Aman   22     85
1  Krish   24     90
2  Rohan   26     88

In [56]:
df = pd.DataFrame({"Name":["Aman","Saurav","Karan","Sujal","Bisnoi","Yadav","Singh"],"Age":[22,25,34,43,23,26,24],"Marks":[78,97,57,86,90,85,99]})

In [41]:
df.head(3)

     Name  Age  Marks
0    Aman   22     78
1  Saurav   25     97
2   Karan   34     57

In [39]:
df.tail()

     Name  Age  Marks
2   Karan   34     57
3   Sujal   43     86
4  Bisnoi   23     90
5   Yadav   26     85
6   Singh   39     99

In [42]:
df.shape

(7, 3)

In [44]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     7 non-null      int64
 2   Marks   7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [47]:
df.describe()

             Age      Marks
count   7.000000   7.000000
mean   30.285714  84.571429
std     8.360907  14.128661
min    22.000000  57.000000
25%    24.000000  81.500000
50%    26.000000  86.000000
75%    36.500000  93.500000
max    43.000000  99.000000

Selecting the data

In [52]:
df[["Name","Marks","Age"]]

     Name  Marks  Age
0    Aman     78   22
1  Saurav     97   25
2   Karan     57   34
3   Sujal     86   43
4  Bisnoi     90   23
5   Yadav     85   26
6   Singh     99   39

In [49]:
df["Age"]

0    22
1    25
2    34
3    43
4    23
5    26
6    39
Name: Age, dtype: int64

Filtering in Pandas

In [54]:
df[df["Marks"]>85]

     Name  Age  Marks
1  Saurav   25     97
3   Sujal   43     86
4  Bisnoi   23     90
6   Singh   39     99

In [57]:
# Multiple Conditions
df[(df["Age"]>23)&(df["Marks"]>85)]

     Name  Age  Marks
1  Saurav   25     97
3   Sujal   43     86
6   Singh   24     99

Sorting + Value Counts

In [58]:
df.sort_values("Marks")

     Name  Age  Marks
2   Karan   34     57
0    Aman   22     78
5   Yadav   26     85
3   Sujal   43     86
4  Bisnoi   23     90
1  Saurav   25     97
6   Singh   24     99

In [59]:
df.sort_values("Marks",ascending= False)

     Name  Age  Marks
6   Singh   24     99
1  Saurav   25     97
4  Bisnoi   23     90
3   Sujal   43     86
5   Yadav   26     85
0    Aman   22     78
2   Karan   34     57

In [60]:
df["Age"].value_counts()

Age
22    1
25    1
34    1
43    1
23    1
26    1
24    1
Name: count, dtype: int64

In [4]:
df = pd.DataFrame({"Name":["Aman","Saurav","Karan","Shubham",None,"Sameer"],
                   "Age":[22,24,None,22,25,26],
                   "Marks":[76,None,97,90,56,None]})
df

      Name   Age  Marks
0     Aman  22.0   76.0
1   Saurav  24.0    NaN
2    Karan   NaN   97.0
3  Shubham  22.0   90.0
4     None  25.0   56.0
5   Sameer  26.0    NaN

In [5]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4   True  False  False
5  False  False   True

In [6]:
df.isnull().sum()

Name     1
Age      1
Marks    2
dtype: int64

In [7]:
df.dropna()

      Name   Age  Marks
0     Aman  22.0   76.0
3  Shubham  22.0   90.0