In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"Name":["Aman","Saurav","Karan","Shubham","Abhishek",None,"Sameer"],
                   "Age":[22,23,None,22,25,24,26],
                   "Marks":[85,None,88,90,56,72,None],
                   "Subject":["Math","Physics","Math","Chemistry","Math","Physics","Chemistry"]})
df

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5      None  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

In [3]:
print(df.shape)
print(df.dtypes)

(7, 4)
Name        object
Age        float64
Marks      float64
Subject     object
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      float64
 2   Marks    5 non-null      float64
 3   Subject  7 non-null      object
dtypes: float64(2), object(2)
memory usage: 356.0+ bytes

In [5]:
df[["Name","Marks"]]

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5      None   72.0
6    Sameer    NaN

In [6]:
df[df["Marks"]>80]

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry

In [7]:
df[(df["Age"]>22) & (df["Marks"]>80)]

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

In [8]:
df["Subject"].value_counts()

Subject
Math         3
Physics      2
Chemistry    2
Name: count, dtype: int64

In [9]:
df.sort_values("Marks",ascending= False)

       Name   Age  Marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     Karan   NaN   88.0       Math
0      Aman  22.0   85.0       Math
5      None  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Saurav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry

In [10]:
df.nsmallest(2, 'Marks')
# df[df['Marks'] == df['Marks'].min()]

       Name   Age  Marks  Subject
4  Abhishek  25.0   56.0     Math
5      None  24.0   72.0  Physics

In [11]:
df.nlargest(2, "Marks")

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0       Math

In [12]:
df.isnull().sum()

Name       1
Age        1
Marks      2
Subject    0
dtype: int64

In [27]:
df.dropna(inplace = True)

In [29]:
cl_df = df.dropna(inplace = False)

In [30]:
cl_df

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math

In [28]:
df

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math

1. Why are the values of Marks in float?
The list contains integer values (85, 88, 90...), but also None values.

The reason: Pandas uses NumPy under the hood. NumPy's integer dtype (int64) cannot represent NaN/None — it has no concept of a "missing integer". So when Pandas encounters None in an integer list, it automatically upcasts the entire column to float64, because float64 can represent NaN (as numpy.nan).

2. Risk of using inplace=True in dropna