In [1]:
import pandas as pd

In [7]:
df = pd.DataFrame({"Name":["Rohit","Virat","Dhoni","Warner",None,"Smith","Ishan","Saurav","Abhishek","Suman"],
                   "Department":["IT","Sales","DSR","Broadcast","IT","Accounts","Sales","Service","DSR","Accounts"],
                   "Role":["Analyst","Manager","Developer","Analyst","Intern","Developer","Manager","Employee","Intern","Analyst"],
                   "Experience":[2,2,5,6,0,2,5,1,0,2],
                   "Salary":[1000,5000,3000,4000,1000,5000,8000,9000,1000,5000],
                   "Score":[84,65,None,90,56,98,None,67,87,93]})
df

       Name Department       Role  Experience  Salary  Score
0     Rohit         IT    Analyst           2    1000   84.0
1     Virat      Sales    Manager           2    5000   65.0
2     Dhoni        DSR  Developer           5    3000    NaN
3    Warner  Broadcast    Analyst           6    4000   90.0
4      None         IT     Intern           0    1000   56.0
5     Smith   Accounts  Developer           2    5000   98.0
6     Ishan      Sales    Manager           5    8000    NaN
7    Saurav    Service   Employee           1    9000   67.0
8  Abhishek        DSR     Intern           0    1000   87.0
9     Suman   Accounts    Analyst           2    5000   93.0

In [4]:
df.groupby('Department')['Salary'].mean()

Department
Accounts     5000.0
Broadcast    4000.0
DSR          2000.0
IT           1000.0
Sales        6500.0
Service      9000.0
Name: Salary, dtype: float64

In [5]:
df.groupby('Role')['Score'].mean()

Role
Analyst      89.0
Developer    98.0
Employee     67.0
Intern       71.5
Manager      65.0
Name: Score, dtype: float64

In [6]:
df.groupby('Department')['Score'].count()

Department
Accounts     2
Broadcast    1
DSR          1
IT           2
Sales        1
Service      1
Name: Score, dtype: int64

In [8]:
df.groupby("Department").size()

Department
Accounts     2
Broadcast    1
DSR          2
IT           2
Sales        2
Service      1
dtype: int64

In [10]:
df.groupby('Department')['Salary'].agg(['mean','max','min','count'])

              mean   max   min  count
Department
Accounts    5000.0  5000  5000      2
Broadcast   4000.0  4000  4000      1
DSR         2000.0  3000  1000      2
IT          1000.0  1000  1000      2
Sales       6500.0  8000  5000      2
Service     9000.0  9000  9000      1

In [12]:
df.groupby('Role')['Score'].agg(['mean','max','min','count'])

           mean   max   min  count
Role
Analyst    89.0  93.0  84.0      3
Developer  98.0  98.0  98.0      1
Employee   67.0  67.0  67.0      1
Intern     71.5  87.0  56.0      2
Manager    65.0  65.0  65.0      1

In [13]:
df.groupby(['Department','Role'])['Salary'].mean()

Department  Role
Accounts    Analyst      5000.0
            Developer    5000.0
Broadcast   Analyst      4000.0
DSR         Developer    3000.0
            Intern       1000.0
IT          Analyst      1000.0
            Intern       1000.0
Sales       Manager      6500.0
Service     Employee     9000.0
Name: Salary, dtype: float64

In [14]:
df.groupby(['Department','Experience'])['Salary'].mean()

Department  Experience
Accounts    2             5000.0
Broadcast   6             4000.0
DSR         0             1000.0
            5             3000.0
IT          0             1000.0
            2             1000.0
Sales       2             5000.0
            5             8000.0
Service     1             9000.0
Name: Salary, dtype: float64